### ISSUE TITLE
Docker-compose up - Error: docker.errors.TLSParameterError

### ISSUE THREAD

**Issue by aaronfranco** [telepat-io/telepat-docker-compose-files#3]
The first /shared/docker-compose.yml file runs without failure. After that I switch to the /telepat/ folder and run docker-compose up, but I get the following error.

````
docker.errors.TLSParameterError: Path to a certificate and key files must be provided through the client_config param. TLS configurations should map the Docker CLI client configurations. See http://docs.docker.com/examples/https/ for API details.
````

I have DOCKER_HOST and DOCKER_CERT_PATH and DOCKER_TLS_VERIFY variables set properly. Am I missing something?

**Comment by andreimarinescu** [comment]
Hi Aaron,

Nope, you're not missing anything. Might it be that you're opening a new console window that doesn't have these environment variables set?

**Comment by aaronfranco** [comment]
In the terminal window, here is the output I'm getting...
````
➜  telepat git:(master) ✗ echo $DOCKER_HOST
"tcp://192.168.99.100:2376"
➜  telepat git:(master) ✗ echo $DOCKER_CERT_PATH
"/Users/aaronfranco/.docker/machine/machines/default"
➜  telepat git:(master) ✗ echo $DOCKER_TLS_VERIFY
1
➜  telepat git:(master) ✗ 
````

**Comment by aaronfranco** [comment]
Here is the full error

````
➜  telepat git:(master) ✗ docker-compose --verbose up
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 39, in main
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 57, in perform_command
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 79, in get_project
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 62, in get_client
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docker_client", line 33, in docker_client
  File "/compose/build/docker-compose/out00-PYZ.pyz/docker.tls", line 46, in __init__
docker.errors.TLSParameterError: Path to a certificate and key files must be provided through the client_config param. TLS configurations should map the Docker CLI client configurations. See http://docs.docker.com/examples/https/ for API details.
````

**Comment by aaronfranco** [comment]
This error was caused by having my DOCKER_CERT_PATH closed in quotes. On to the next error :)

**Comment by aaronfranco** [comment]
````
➜  telepat git:(master) ✗ echo $DOCKER_CERT_PATH
"/Users/aaronfranco/.docker/machine/machines/default"
➜  telepat git:(master) ✗ export DOCKER_CERT_PATH=/Users/aaronfranco/.docker/machine/machines/default
````

**Comment by aaronfranco** [comment]
I also got an error about having an invalid port
````
docker-compose up                                                          
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 39, in main
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 57, in perform_command
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 79, in get_project
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 62, in get_client
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docker_client", line 37, in docker_client
  File "/compose/build/docker-compose/out00-PYZ.pyz/docker.clientbase", line 34, in __init__
  File "/compose/build/docker-compose/out00-PYZ.pyz/docker.utils.utils", line 277, in parse_host
docker.errors.DockerException: ('Invalid port: %s', '192.168.99.100:2376"')
````
This was also caused by having quotes around my DOCKER_HOST env. variable.

**Comment by andreimarinescu** [comment]
Yep, we found docker to fail in the weirdest ways as well. Good to know that you're back on track! Ping us if there anything we can help out with.

**Comment by aaronfranco** [comment]
Thank you @andreimarinescu! keep up the great work :+1:
